<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array(
	'ILLEGAL_ARGUMENT'      => '参数不正确',
	'TRADE_NOT_EXIST'  => '交易不存在',
	'TRADE_STATUS_NOT_AVAILD' => '交易状态非担保交易或COD交易',		
    'ILLEGAL_SIGN'  => '签名不正确',
    'ILLEGAL_DYN_MD5_KEY'=> '动态密钥信息错误',
    'ILLEGAL_ENCRYPT'=> '加密不正确',
    'ILLEGAL_ARGUMENT'=> '参数不正确',
    'ILLEGAL_SERVICE'=> 'Service参数不正确',
);
