<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array(
	'forbidden'      => '禁止访问',
	'no_such_order'  => '没有该订单',
	'no_alipay_payment' => '支付方式不正确',		
    'order_info_empty'  => '订单信息为空',
    'notify_unauthentic'=> '通知验证不通过',
    'sign_inconsistent'=> '签名不一致',
    'order_inconsistent'=> '实际支付的订单与应支付的订单不一致',
    'price_inconsistent'=> '实际支付与应支付的价格不一致',
    'undefined_status'=> '未定义订单状态',
    'pay_successed' => '支付成功。',
    'pay_successed_desc'  => '您已成功支付了，请等待卖家给您发货，您想：',
);
